const routes = {
  home: '/',
  admin: '/admin',
  adminProfile: '/admin/profile',
  accountList: '/admin/account-list',
  createAccount: '/admin/create-account',
  moderator: '/moderator',
  manager: '/manager',
  overview: '/moderator/overview',
  productList: '/manager/product-list',
  createProduct: '/manager/create-product',
  updateProduct: '/manager/update-product/:productId',
  categoryList: '/manager/category-list',
  ticketList: '/manager/ticket-list',
  ticketDashboard: '/manager/ticket-dashboard',
  moderatorSettings: '/manager/settings',
  login: '/login',
  loginGoogle: '/login/google',
  register: '/register',
  logout: '/logout',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  appResetPassword: '/app/reset-password',
  user: '/user',
  userProfile: '/user/profile',
  userChangePassword: '/user/change-password',
  404: '/404',
  error: '*',
};

export default routes;
