export const GET_ME_QUERY_KEY = 'GET_ME_QUERY_KEY';

export const GET_TABLE_PRODUCTS_QUERY_KEY = 'GET_TABLE_PRODUCTS_QUERY_KEY';

export const GET_PRODUCT_CATEGORIES_QUERY_KEY = 'GET_PRODUCT_CATEGORIES_QUERY_KEY';
export const GET_PRODUCT_BY_ID_QUERY_KEY = 'GET_PRODUCT_BY_ID_QUERY_KEY';

export const GET_TABLE_TICKETS_QUERY_KEY = 'GET_TABLE_TICKETS_QUERY_KEY';
